
export const API_ENDPOINTS = {
    // Common / Player
    usersMe: '/users/me',
    userProfile: (publicId: string) => `/users/${publicId}`,
    arenas: '/arenas',
    arenaTop: (limit = 4) => `/arenas/top?limit=${limit}`,
    arenaDetail: (slug: string) => `/arenas/${slug}`,
    arenaSlots: (publicId: string, date: string) => `/arenas/${publicId}/slots?date=${date}`,
    arenaReviews: (publicId: string, limit = 10) => `/arenas/${publicId}/reviews?limit=${limit}`,
    arenaCreateReview: (publicId: string) => `/arenas/${publicId}/reviews`,
    arenaReviewEligibility: (publicId: string) => `/arenas/${publicId}/reviews/eligibility`,
    uploadSign: '/uploads/sign',

    // Live scoring (official's device)
    matchLive: (publicId: string) => `/matches/${publicId}/live`,
    matchLiveStart: (publicId: string) => `/matches/${publicId}/live/start`,
    matchLivePoint: (publicId: string) => `/matches/${publicId}/live/point`,
    matchLiveUndo: (publicId: string) => `/matches/${publicId}/live/undo`,
    matchLiveEvent: (publicId: string) => `/matches/${publicId}/live/event`,
    matchLiveConfirm: (publicId: string) => `/matches/${publicId}/live/confirm`,
    officialMyMatches: '/officials/me/matches',
    matchStats: (publicId: string) => `/matches/${publicId}/live/stats`,
    matchConfirmResult: (publicId: string) => `/matches/${publicId}/result/confirm`,
    matchOfficialFee: (publicId: string) => `/matches/${publicId}/official-fee`,
    matchCollectOfficialFee: (publicId: string) => `/matches/${publicId}/official-fee/collect`,
    matchProposeOfficial: (publicId: string) => `/matches/${publicId}/official`,
    matchConfirmOfficial: (publicId: string) => `/matches/${publicId}/official/confirm`,
    officials: '/officials',
    challengeDetail: (publicId: string) => `/challenges/${publicId}`,
    challengeQuote: '/challenges/quote',
    challenges: (limit = 20) => `/challenges?limit=${limit}`,
    challengeCreate: '/challenges',
    myBookings: '/bookings',
    teamsMine: '/teams/mine',
    teamCreate: '/teams',
    leaderboard: (sport = 'badminton', format = 'singles', limit = 50) =>
        `/leaderboards?sport=${sport}&format=${format}&limit=${limit}`,
    publicRecentMatches: (limit = 5) => `/public/matches/recent?limit=${limit}`,
    publicPlayer: (publicId: string) => `/public/players/${publicId}`,
    officialDetail: (publicId: string) => `/officials/${publicId}`,

    // Booking / checkout
    bookingHold: '/bookings/hold',
    bookingConfirm: '/bookings',
    bookingDetail: (publicId: string) => `/bookings/${publicId}`,
    wallet: '/wallet',
    walletTransactions: (limit = 20) => `/wallet/transactions?limit=${limit}`,
    walletTopupOrder: '/wallet/topup/order',
    walletTopupVerify: '/wallet/topup/verify',
    walletWithdraw: '/wallet/withdraw',
    walletWithdrawals: '/wallet/withdrawals',

    // Auth
    otpRequest: '/auth/otp/request',
    otpVerify: '/auth/otp/verify',
    socketToken: '/auth/socket-token',

    // Owner / Partner panel
    ownerApply: '/owner/apply',
    ownerApplication: '/owner/application',
    ownerApplicationStep: (step: number) => `/owner/application/step/${String(step)}`,
    ownerApplicationSubmit: '/owner/application/submit',
    ownerVerifyPhone: (publicId: string) => `/owner/apply/${publicId}/verify-phone`,
    ownerDashboard: '/owner/dashboard',
    ownerArenas: '/owner/arenas',
    ownerArenaDetail: (publicId: string) => `/owner/arenas/${publicId}`,
    ownerBookings: (limit = 8) => `/owner/bookings?limit=${limit}`,
    ownerCourts: (arenaPublicId: string) => `/owner/arenas/${arenaPublicId}/courts`,
    ownerCourt: (courtId: string) => `/owner/courts/${courtId}`,
    ownerPricingRules: '/owner/pricing-rules',
    ownerPricingRulesFor: (arenaPublicId: string) =>
        `/owner/pricing-rules?arenaPublicId=${arenaPublicId}`,
    ownerPricingPreview: (arenaPublicId: string) =>
        `/owner/pricing-preview?arenaPublicId=${arenaPublicId}`,
    ownerBlockSlots: '/owner/slots/block',
    ownerSettlements: '/owner/settlements',
    ownerSettlement: (publicId: string) => `/owner/settlements/${publicId}`,

    // Admin panel / Ops console
    adminOverview: '/admin/overview',
    adminApplications: '/admin/applications',
    adminApplicationDetail: (publicId: string) => `/admin/applications/${publicId}`,
    adminVerifyApplication: (publicId: string) => `/admin/applications/${publicId}/verification`,
    adminApproveApplication: (publicId: string) => `/admin/applications/${publicId}/approve`,
    adminRejectApplication: (publicId: string) => `/admin/applications/${publicId}/reject`,
    adminDisputes: '/admin/disputes',
    adminWithdrawals: (status = 'pending') => `/admin/withdrawals?status=${status}`,
    adminReviewWithdrawal: (publicId: string) => `/admin/withdrawals/${publicId}/review`,
    adminConfig: '/admin/config',
} as const;
